name: My second Github Workflow
on: [push]
jobs:
	Check-versions:
		runs-on: ubuntu-latest
		steps:
			- run: echo "Checking python version"
			- run: python --version
			- uses: actions/checkout@v3

	Installing-pytest:
		runs-on: ubuntu-latest
		steps:
			- run: echo "Installing Pytest"
			- run: |
				python -m pip install --upgrade pip
				pip install -U pytest
			- run: echo "Checking Pytest version"
			- run: pytest --version
			uses: actions/checkout@v3

	Runs-test:
		runs-on: ubuntu-latest
		steps:
			- run: find . -name '*.py' exec pytest {} \;
			- uses: actions/checkout@v3
	
	Build-app-image:
		runs-on: ubuntu-latest
		steps:
			- run: find . -name 'Dockerfile' -exec docker build --tag test-app . {} \;
			- uses: actions/checkout@v3