name: My second Github Workflow
on: [push]
jobs:
   runs-on: ubuntu-latest
      steps:
         - run: echo "Checking python version"
	 - run: python --version
	 - run: echo "Installing Pytest"
	 - run: |
	      python -m pip install --upgrade pip
	      pip install -U pytest
	 - run: echo "Checking Pytest version"
	 - run: pytest --version
	 - run: find . -name '*.py' exec pytest {} \;
	 - run: find . -name 'Dockerfile' -exec docker build --tag test-app . {} \;
	 - uses: actions/checkout@v3
